/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author jefer
 */
public class TelaCalculadora2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora2
     */
    public TelaCalculadora2() {
        initComponents();
        lblResultado.setVisible(false);
        lblInfoNum.setVisible(false);
        lblInfoQtde.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JSpinner();
        btnPotencia = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnPorcentagem = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblSimbolo = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        txtNum2 = new javax.swing.JSpinner();
        lblInfoNum = new javax.swing.JLabel();
        lblInfoQtde = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 35)); // NOI18N
        jLabel1.setText("Calculadora");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contabilidade (1).png"))); // NOI18N

        txtNum1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtNum1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1000.0d, 1.0d));

        btnPotencia.setBackground(new java.awt.Color(204, 204, 255));
        btnPotencia.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btnPotencia.setText("Potência");
        btnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaActionPerformed(evt);
            }
        });

        btnRaiz.setBackground(new java.awt.Color(204, 204, 255));
        btnRaiz.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btnRaiz.setText("Raiz Quadrada");
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        btnPorcentagem.setBackground(new java.awt.Color(204, 204, 255));
        btnPorcentagem.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btnPorcentagem.setText("Porcentagem");
        btnPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentagemActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(204, 255, 204));
        btnLimpar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblSimbolo.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblSimbolo.setText("=");

        lblResultado.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblResultado.setText("Resultado");

        btnVoltar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/de-volta.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txtNum2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtNum2.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1000.0d, 1.0d));

        lblInfoNum.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblInfoNum.setText("Número");

        lblInfoQtde.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblInfoQtde.setText("Quantidade %");

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel3.setText("Dica: Selecione primeiramente a operação que deseja realizar e depois adicione os números.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPotencia)
                                    .addComponent(btnPorcentagem)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRaiz)
                                        .addGap(218, 218, 218)
                                        .addComponent(btnLimpar))
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(lblInfoNum)
                                .addGap(106, 106, 106)
                                .addComponent(lblInfoQtde))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblSimbolo)
                                .addGap(31, 31, 31)
                                .addComponent(lblResultado)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoNum)
                    .addComponent(lblInfoQtde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSimbolo)
                    .addComponent(lblResultado)
                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnPotencia)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRaiz)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(btnPorcentagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        // TODO add your handling code here:
        txtNum2.setVisible(false);
        lblInfoNum.setVisible(false);
        lblInfoQtde.setVisible(false);
        double num1 = Double.parseDouble(txtNum1.getValue().toString());
        double raiz = Math.sqrt(num1);
        lblResultado.setText(String.format("%.2f",(raiz)));
        lblResultado.setVisible(true);
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        TelaOpcoes tela = new TelaOpcoes();
        tela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaActionPerformed
        // TODO add your handling code here:
        lblInfoNum.setVisible(false);
        lblInfoQtde.setVisible(false);
        double num1 = Double.parseDouble(txtNum1.getValue().toString());
        double num2 = Double.parseDouble(txtNum2.getValue().toString());
        double potencia = Math.pow(num1, num2);
        lblResultado.setText(String.format("%.2f",(potencia)));
        lblResultado.setVisible(true);
    }//GEN-LAST:event_btnPotenciaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtNum2.setVisible(true);
        txtNum1.setValue(0);
        txtNum2.setValue(0);
        lblResultado.setVisible(false);
        lblInfoNum.setVisible(false);
        lblInfoQtde.setVisible(false);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentagemActionPerformed
        // TODO add your handling code here:
        lblInfoNum.setVisible(true);
        lblInfoQtde.setVisible(true);
        double num1 = Double.parseDouble(txtNum1.getValue().toString());
        double num2 = Double.parseDouble(txtNum2.getValue().toString());
        double porcentagem = num1 * num2 / 100;
        lblResultado.setText(String.format("%.2f",(porcentagem)));
        lblResultado.setVisible(true);
    }//GEN-LAST:event_btnPorcentagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPorcentagem;
    private javax.swing.JButton btnPotencia;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblInfoNum;
    private javax.swing.JLabel lblInfoQtde;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSimbolo;
    private javax.swing.JSpinner txtNum1;
    private javax.swing.JSpinner txtNum2;
    // End of variables declaration//GEN-END:variables
}
